apiVersion: v1
kind: Pod
metadata:
  name: weather-pod
  namespace: default
spec:
  volumes:
    - emptyDir: {}
      name: weather-data
  initContainers:
    - name: download-config
      image: curlimages/curl:7.85.0
      args: ["https://api.open-meteo.com/v1/forecast?latitude=37.54443878&longitude=127.03744246&current_weather=true", "-o", "/usr/share/nginx/html/index.html"]
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: weather-data
  containers:
    - image: nginx:1.25.3-alpine
      name: nginx-container
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: weather-data
